[package]
name = "idnx"
version = "0.1.0"
edition = "2024"
authors = ["Sriram <marirs@gmail.com>"]
description = "Network Identification & Deep eXploration Tool"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.43", features = ["full"] }
colored = "3.0"
ipnet = "2.11"
indicatif = "0.17"
get_if_addrs = "0.5"
comfy-table = "7.1"
libc = "0.2"
